### ISSUE TITLE
Incorrect comment syntax (“#”) in "Debugging workflows" code example (Section 1.5)

### ISSUE THREAD

**Issue by arose20** [nextflow-io/training#676]
Description:
Within the side quest **Debugging Workflows**, section 1.5 - Bad practice syntax errors when using the VSCode extension, the `badpractice_syntax.nf (fixed)` example uses a `#` for the commenting within the workflow so if a user copies directly it will run a Script compilation error. 

Current example:
```
workflow {
    input_ch = Channel.of('sample1', 'sample2', 'sample3')  # Moved inside workflow block
    PROCESS_FILES(input_ch)
}

```

Corrected example:
```
workflow {
    input_ch = Channel.of('sample1', 'sample2', 'sample3')  // Moved inside workflow block
    PROCESS_FILES(input_ch)
}
```

<img width="925" height="860" alt="Image" src="https://github.com/user-attachments/assets/a13386f1-56dc-47ca-b82c-2a7c1b5ef148" />

**Comment by vdauwera** [comment]
fixed, thank you!
